# Generated by Django 4.0.6 on 2024-05-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0002_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='apellidoy7',
            new_name='apellido',
        ),
    ]
