# Generated by Django 4.0.6 on 2024-06-25 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0009_director_fotografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='fotografia',
            new_name='foto',
        ),
    ]
