# Generated by Django 5.0.6 on 2024-08-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0010_rename_fotografia_director_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('direccion', models.CharField(default='', max_length=150)),
                ('telefono', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
